#!/usr/bin/env python3
"""Publication figures for paper 2 (standalone — reads saved npz results).

Fig 1: assumed vs measured zonation gradients (context figure).
Fig 2: PK-calibrated NAC efficacy window (the 8-hour-rule figure).
Fig 3: NAC PK calibration — pericentral GSH recovery vs the 50%-by-12h
       criterion, for the no-NAC reference and M_max = 1, 2, 4, 8.
Fig 4: staggered vs single ingestion (already generated by nac_staggered.py).

All text uses high-contrast ink (no grey), per the accessibility standard
adopted in paper 1's figures.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys_path = Path(__file__).parent
import sys  # noqa: E402
sys.path.insert(0, str(sys_path))
from zonated_apap_model import SCHEMES, POS, N_HEPATOCYTES  # noqa: E402

BASE = Path(__file__).resolve().parent.parent
FIGDIR = BASE / "figures"
RES = BASE / "results"

ASSUMED_C = "#eb6834"   # categorical orange
MEASURED_C = "#2a78d6"  # categorical blue
INK = "#0b0b0b"
INK2 = "#52514e"
GRID = "#e1e0d9"
BASELINE = "#c3c2b7"

plt.rcParams.update({
    "font.size": 9, "axes.edgecolor": BASELINE, "axes.linewidth": 0.8,
    "axes.labelcolor": INK2, "xtick.color": INK2, "ytick.color": INK2,
    "axes.titleweight": "bold", "axes.titlesize": 9.5, "figure.facecolor": "white",
    "axes.facecolor": "white", "grid.color": GRID, "grid.linewidth": 0.6,
    "legend.frameon": False, "savefig.dpi": 300, "savefig.bbox": "tight",
})

PARAM_LABEL = {
    "k450": "CYP450  (k450)",
    "kG": "Glucuronidation  (kG)",
    "kS": "Sulfation  (kS)",
    "kGSH": "GSH conjugation  (kGSH)",
    "bG": "GSH synthesis  (bG)",
}


def ramp(mp, mc):
    return mp + (mc - mp) * POS


def fig1_gradients():
    params = ["k450", "kG", "kS", "kGSH", "bG"]
    fig, axes = plt.subplots(1, 5, figsize=(10.5, 2.5), sharex=True, sharey=True)
    x = np.arange(1, N_HEPATOCYTES + 1)
    for ax, pkey in zip(axes, params):
        assumed = ramp(*SCHEMES["assumed"][pkey])
        measured = ramp(*SCHEMES["measured"][pkey])
        ax.plot(x, assumed, color=ASSUMED_C, ls="--", lw=2)
        ax.plot(x, measured, color=MEASURED_C, ls="-", lw=2)
        ax.axhline(1.0, color=BASELINE, lw=0.8)
        ax.set_yscale("log", base=2)
        ax.set_yticks([0.5, 1, 2, 4])
        ax.set_yticklabels(["0.5×", "1×", "2×", "4×"])
        ax.set_ylim(0.25, 5)
        ax.set_title(PARAM_LABEL[pkey], fontsize=8)
        ax.grid(True, which="both", lw=0.6)
        ax.set_xticks([1, 16])
        ax.set_xticklabels(["portal", "central"], fontsize=7.5)
        ax.tick_params(axis="y", labelsize=7.5)
    axes[0].set_ylabel("relative activity\n(fold vs uniform)", fontsize=8)
    axes[3].annotate("direction\nreversed", xy=(16, 1.85), xytext=(7, 3.0),
                     fontsize=7, color=INK2, ha="center",
                     arrowprops=dict(arrowstyle="->", lw=0.8, color=INK2))
    from matplotlib.lines import Line2D
    handles = [Line2D([], [], color=ASSUMED_C, ls="--", lw=2,
                      label="assumed"),
               Line2D([], [], color=MEASURED_C, ls="-", lw=2,
                      label="measured")]
    axes[0].legend(handles=handles, loc="lower right", fontsize=7.5,
                   frameon=False)
    fig.savefig(FIGDIR / "fig1_gradients.png")
    plt.close(fig)


def fig2_window():
    d = np.load(RES / "nac_window_pk.npz")
    starts = d["starts"]
    fig, axes = plt.subplots(1, 2, figsize=(7.6, 3.0), sharey=True)
    for ax, dose in zip(axes, (4, 16)):
        for scheme, color in (("assumed", ASSUMED_C), ("measured", MEASURED_C)):
            prot = d[f"prot_{scheme}_{dose}g"]
            ax.plot(starts, prot, "-o", color=color, lw=2, ms=5, label=scheme)
        ax.set_title(f"{dose} g", fontsize=9.5)
        ax.set_xlabel("NAC start time after ingestion (h)", fontsize=8)
        ax.set_xticks(starts)
        ax.tick_params(labelsize=8)
        ax.grid(True, lw=0.6)
        ax.axvspan(8, 12, color=GRID, alpha=0.5, zorder=0)
        ax.text(10, 4, "late\nwindow", fontsize=7, color=INK2, ha="center")
    axes[0].set_ylabel("reduction in peak pericentral\nadducts vs no NAC (%)",
                       fontsize=8)
    axes[0].legend(fontsize=8, loc="upper right")
    fig.savefig(FIGDIR / "fig2_nac_window.png")
    plt.close(fig)


def fig3_calibration():
    d = np.load(RES / "nac_calibration.npz")
    t_h = d["t_h"]
    baseline = float(d["baseline"])
    blues = {1: "#b7d3f6", 2: "#5598e7", 4: "#1c5cab", 8: "#104281"}
    fig, ax = plt.subplots(figsize=(5.4, 3.4))

    # no-NAC reference (M_max = 0)
    ax.plot(t_h, d["G_M0"], color=INK2, ls="--", lw=1.8, label="no NAC")
    for M in (1, 2, 4, 8):
        lw = 2.4 if M == 4 else 1.4
        ax.plot(t_h, d[f"G_M{M}"], color=blues[M], lw=lw, label=f"M_max = {M}")
    ax.axhline(0.5 * baseline, color=INK, lw=1.2, ls=":")
    ax.text(23.6, 0.5 * baseline, " criterion:\n 50% of baseline",
            fontsize=7, color=INK, va="center", ha="right")
    ax.axvline(12, color=BASELINE, lw=1.0)
    ax.set_xlabel("time after 16 g ingestion (h)", fontsize=8)
    ax.set_ylabel("pericentral GSH (nmol)", fontsize=8)
    ax.set_xlim(0, 24)
    ax.tick_params(labelsize=8)
    ax.grid(True, lw=0.6)
    ax.legend(fontsize=8, loc="upper left")
    ax.annotate("calibrated:\nM_max = 4", xy=(12, 0.5 * baseline),
                xytext=(14.5, 3.2e-3), fontsize=8, color=INK,
                arrowprops=dict(arrowstyle="->", lw=0.9, color=INK))
    fig.savefig(FIGDIR / "fig3_calibration.png")
    plt.close(fig)


def main():
    FIGDIR.mkdir(exist_ok=True)
    fig1_gradients()
    fig2_window()
    fig3_calibration()
    for f in sorted(FIGDIR.glob("*.png")):
        print("wrote", f.name)


if __name__ == "__main__":
    main()
